### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f609'

### ISSUE THREAD

**Issue by sebastien-helbert** [cfrezier/devoxx2adoc#4]
`UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f609' in position 0: character maps to <undefined> occurs` when running generate.py

**Comment by sylvainmetayer** [comment]
Hello, 

Could you share some information about your setup please ? I can't reproduce this issue on Fedora with Python 3.12

**Comment by sebastien-helbert** [comment]
Got it with Windows (WSL), Python 3.11.9
